ALTER TABLE pb_media ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE pb_media ADD COLUMN last_modified TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE pb_media ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
