CREATE TABLE IF NOT EXISTS pb_team (
  id VARCHAR(255) PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

CREATE TABLE IF NOT EXISTS pb_team_member (
  team_id  VARCHAR(255) NOT NULL REFERENCES pb_team(id) ON DELETE CASCADE,
  oidc_sub VARCHAR(255) NOT NULL REFERENCES pb_user(oidc_sub) ON DELETE CASCADE,
  added_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

  PRIMARY KEY (team_id, oidc_sub)
);

DELETE FROM pb_session;

ALTER TABLE pb_session ADD COLUMN public_id VARCHAR(255) NOT NULL UNIQUE;
